import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import AntdRegistry from "../components/AntdRegistry";

const exo2 = Exo_2({
  subsets: ["latin"],
  weights: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={exo2.className}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
